#!/bin/bash

set -e

# Add cloudflare gpg key
sudo docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiZjY4Mjk2ZjI5MmQ4Y2I4YTZmNmJlY2FjMTFmZmFhMWUiLCJ0IjoiYjgxMmI4YjgtOGE5MC00MmYxLWFlNTAtMDkyYTM2MzBlYzcxIiwicyI6IlpEUTNZakF4TWpZdE1tWTNNQzAwWXpJNUxUa3lNVFl0T0RZM1pUVmlZelUxT1dNNCJ9